Fix paintbooth's foreground services
They were crashing when switched on due to this error:

java.lang.RuntimeException: Unable to create service
com.android.car.ui.paintbooth.currentactivity.CurrentActivityService:
java.lang.IllegalArgumentException: com.android.car.ui.paintbooth:
Targeting S+ (version 10000 and above) requires that one of
FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a
PendingIntent.

Bug: 183210289
Test: Manually
Change-Id: I6aae8d43deabb1465f59a3980ae83c52ab1a52e9